name: Android CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest
    strategy:
      matrix:
        api-level: [29]
        target: [default, google_apis]
    steps:
      - uses: actions/checkout@v2
      - name: set up JDK 20
        uses: actions/setup-java@v3
        with:
          java-version: '20'
          distribution: 'zulu'
          cache: gradle
      - uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ github.repository }}-${{ hashFiles('**/*.gradle*') }}

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew build
      - name: Checks
        run: ./gradlew check
      - name: Instrumentation Checks
        uses: ReactiveCircus/android-emulator-runner@v2.30.1
        with:
          api-level: ${{ matrix.api-level }}
          target: ${{ matrix.target }}
          disable-animations: true
          script: |
            adb shell 'echo "chrome --disable-fre --no-default-browser-check --no-first-run" > /data/local/tmp/chrome-command-line'
            ./gradlew connectedCheck

